// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package model

import (
	"database/sql"
)

type MstCustomer struct {
	ID          string
	Name        sql.NullString
	PhoneNumber sql.NullString
	UserID      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type MstEmployee struct {
	ID          string
	Name        sql.NullString
	PhoneNumber sql.NullString
	UserID      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type MstUser struct {
	ID         string
	Username   sql.NullString
	Password   sql.NullString
	Role       sql.NullString
	ResetToken sql.NullString
	IsActive   sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
