// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package model

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO mst_user (
  id, username, password, role, is_active, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type CreateUserParams struct {
	ID        string
	Username  sql.NullString
	Password  sql.NullString
	Role      sql.NullString
	IsActive  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM mst_user
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, role, is_active, created_at, updated_at
FROM mst_user
WHERE id = $1
`

type GetUserRow struct {
	ID        string
	Username  sql.NullString
	Role      sql.NullString
	IsActive  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsername = `-- name: GetUsername :one
SELECT id, username, role, is_active, created_at, updated_at
FROM mst_user
WHERE username = $1
`

type GetUsernameRow struct {
	ID        string
	Username  sql.NullString
	Role      sql.NullString
	IsActive  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUsername(ctx context.Context, username sql.NullString) (GetUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUsername, username)
	var i GetUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, username, role, is_active, created_at, updated_at
FROM mst_user
ORDER BY created_at DESC
`

type ListUserRow struct {
	ID        string
	Username  sql.NullString
	Role      sql.NullString
	IsActive  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListUser(ctx context.Context) ([]ListUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRow
	for rows.Next() {
		var i ListUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE mst_user 
SET username = $2, password = $3, role = $4, is_active = $5, updated_at = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID        string
	Username  sql.NullString
	Password  sql.NullString
	Role      sql.NullString
	IsActive  sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
